# Generated by Django 4.2.26 on 2025-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=20)),
                ('post_status', models.CharField(max_length=20)),
                ('post_title', models.TextField()),
            ],
            options={
                'db_table': 'wpsv_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMetalLookup',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'wpsv_wc_product_meta_lookup',
                'managed': False,
            },
        ),
    ]
