# Generated by Django 4.2.26 on 2025-11-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMetalLookup',
        ),
    ]
