# Generated by Django 4.2.26 on 2025-11-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_delete_productmetallookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetaLookup',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'wpsv_wc_product_meta_lookup',
                'managed': False,
            },
        ),
    ]
